import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const layout=read('app/(app)/_layout.tsx');const header=read('src/features/navigation/AppHeader.tsx');const chrome=read('src/features/navigation/AppChrome.tsx');const motion=read('src/features/navigation/navigationMotion.ts');const tokens=read('src/design/environmentTokens.ts');const components=read('src/design/componentTokens.ts');const pairing=read('src/features/pairing/PairingScreen.tsx');const hero=read('src/features/pairing/PairingHero.tsx');const initial=read('src/features/pairing/PairingInitialState.tsx');const waiting=read('src/features/pairing/PairingWaitingState.tsx');const joining=read('src/features/pairing/PairingJoinState.tsx');const scene=read('src/features/bowl/BowlScene.tsx');const settings=read('src/features/settings/SettingsScreen.tsx');const labRoute=read('app/(app)/bowl-lab.tsx');
const luminance=(hex)=>{const c=[1,3,5].map((index)=>Number.parseInt(hex.slice(index,index+2),16)/255).map((value)=>value<=.04045?value/12.92:((value+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];};
const contrast=(first,second)=>(Math.max(luminance(first),luminance(second))+.05)/(Math.min(luminance(first),luminance(second))+.05);

test('one Pebble navigation shell owns every signed-in header',()=>{assert.match(layout,/AppChrome/);assert.match(chrome,/<AppHeader \/>/);assert.match(layout,/headerShown: false/);assert.doesNotMatch(layout,/#15191E|headerStyle|headerTintColor/);assert.match(header,/pathname === '\/bowl'.*pathname === '\/pairing'/);assert.match(header,/t\('app\.settings'\)/);assert.match(header,/router\.canGoBack\(\)/);assert.match(header,/router\.replace\(home\)/);assert.match(header,/developmentClearance/);assert.match(header,/MIN_TOUCH_TARGET/);});
test('navigation motion is restrained and reduced-motion aware',()=>{assert.match(motion,/headerEntrance: 210/);assert.match(motion,/titleTransition: 200/);assert.match(motion,/pressedScale: 0\.97/);assert.match(header,/useReducedMotion/);assert.doesNotMatch([header,motion].join('\n'),/bounce|spring/i);});
test('luminous mineral tokens replace charcoal as the global default',()=>{for(const value of ['#DCE6E5','#EEECE5','#E8DED2','#F4F1EB','#C8D0CB','#303937','#789287','#9B9D95','#B9B9AE','#D0CDC1'])assert.match(tokens,new RegExp(value));assert.match(components,/primaryButton/);assert.doesNotMatch([layout,tokens].join('\n'),/#15191E|#182126|#27343A/);});
test('all luminous time stops keep essential functional text at AA contrast',()=>{const secondary=tokens.match(/textSecondary: '(#[0-9A-F]{6})'/)[1];const primary=tokens.match(/textPrimary: '(#[0-9A-F]{6})'/)[1];const error=tokens.match(/error: '(#[0-9A-F]{6})'/)[1];const backgrounds=[...tokens.matchAll(/(?:upper|centre|lower): '(#[0-9A-F]{6})'/g)].map((match)=>match[1]);assert.ok(backgrounds.length>=18);for(const background of backgrounds){assert.ok(contrast(primary,background)>=4.5,`${primary} on ${background}`);assert.ok(contrast(secondary,background)>=4.5,`${secondary} on ${background}`);assert.ok(contrast(error,background)>=4.5,`${error} on ${background}`);}});
test('pairing is mutually exclusive initial, waiting, and joining state',()=>{assert.match(pairing,/type PairingFlow = 'initial' \| 'waiting' \| 'joining'/);assert.match(pairing,/flow === 'initial'.*PairingInitialState/);assert.match(pairing,/flow === 'waiting'.*PairingWaitingState/);assert.match(pairing,/flow === 'joining'.*PairingJoinState/);assert.match(initial,/createLabel/);assert.match(initial,/joinLabel/);assert.doesNotMatch(initial,/TextInput/);assert.match(joining,/TextInput/);assert.match(joining,/onCancel/);assert.match(pairing,/KeyboardAvoidingView/);});
test('waiting ritual keeps one physical hero bowl while prioritizing sharing',()=>{assert.match(hero,/composition="pairing-single"/);assert.doesNotMatch(scene,/SecondaryBowl|position=\{\[-0\.72/);assert.equal((scene.match(/<BowlMesh/g)??[]).length,2);assert.doesNotMatch([hero,waiting].join('\n'),/secondBowl|borderRadius: 999/);assert.match(waiting,/selectable/);assert.match(waiting,/copyLabel/);assert.match(waiting,/shareLabel/);assert.match(waiting,/expanded: false/);});
test('pairing hero and controls remain responsive and accessible',()=>{assert.match(pairing,/Math\.max\(240, Math\.min\(360, window\.height \* 0\.34\)\)/);assert.match(hero,/width: '100%'/);assert.match(waiting,/accessibilityLiveRegion|copiedMessage/);assert.match(joining,/accessibilityLabel=\{inputLabel\}/);assert.match(joining,/placeholderTextColor=\{colors\.textMuted\}/);assert.match(pairing,/reducedMotion/);});
test('Settings remains scrollable and development-only Lab stays protected',()=>{assert.match(settings,/<ScrollView/);assert.match(settings,/\{__DEV__ \?/);assert.match(labRoute,/if\(!__DEV__\)return<Redirect/);});
