export const en = {
  app:{name:'Pebble',loading:'Loading Pebble',retry:'Try again',connectionError:'Could not load your connection.',settings:'Settings',back:'Back',bowlHome:'Return to your bowl',notConfigured:'Pebble is not configured on this device.',continue:'Continue',skip:'Skip'},
  onboarding:{first:'A pebble means: I thought of you.',second:'The same pebbles travel between your two bowls.',third:'There is no need to reply. An empty bowl can remain quiet.'},
  auth:{signIn:'Sign in',createProfile:'Create profile',access:'Enter your private connection.',displayName:'Display name',email:'Email',password:'Password',createAccount:'Create profile',existingAccount:'I already have access',createError:'Could not create profile.',signInError:'Could not sign in.',emailHint:'Use a valid email address.',passwordHint:'Use at least 6 characters.'},
  pairing:{begin:'Begin a connection.',create:'Create invitation',join:'Join with an invitation',joinChoice:'Join with an invitation',joinTitle:'Join a connection.',joinAction:'Join connection',useOther:'Use another invitation',waitingTitle:'Your bowl is ready.',waitingSecondary:'The other person has not joined yet.',invitation:'Invitation code',shareOnce:'This invitation can be used once. Share it only with the person you choose.',copy:'Copy invitation',share:'Share invitation',copied:'Invitation copied.',createError:'Could not create the connection.',joinError:'Could not join the connection.',activeConnection:'You already have an active connection.',invalid:'This invitation is not available.',expired:'This invitation has expired.',used:'This invitation has already been used.',full:'This connection already has two people.',network:'Could not connect. Try again.',waiting:'Your bowl is ready. The other person has not joined yet.'},
  bowl:{title:'Your bowl',empty:'The bowl is empty.',accessibility:'Your bowl and the pebbles you hold',incoming:'Newly arrived pebble',held:'Pebble in your bowl',holdHint:'Press and hold a pebble to send it.',sendAccessibilityHint:'Hold to send this pebble.',touchAccessibilityHint:'Tap to touch it, or hold to send it.',loading:'Loading your bowl',closed:'This connection has ended.',sendError:'The pebble could not travel. Try again.',touchError:'The pebble could not be touched. Try again.',loadError:'Your bowl could not be loaded.'},
  settings:{title:'Settings',profile:'Profile',language:'Language',connection:'Connection',notifications:'Notifications',account:'Account',development:'Development',bowlLab:'Open Bowl Lab',glLayoutProbe:'GL Layout Probe',rawGLViewProbe:'Raw GLView Probe',developmentOnly:'Available only in development builds.',displayName:'Display name',accountEmail:'Account email',currentLanguage:'Current language',systemDefault:'System default',activeConnection:'Active connection',pastConnections:'Past connections',permission:'Notification permission',sounds:'Sounds',soundsDetail:'Quiet bowl sounds, when recordings are available',enabled:'Allowed',disabled:'Not allowed',unavailable:'Unavailable',signOut:'Sign out',deleteAccount:'Delete account',endConnection:'End connection',beginNew:'Begin a connection',noPast:'No past connections yet.',statusActive:'Connected',statusWaiting:'Waiting',statusClosed:'Ended',partner:'Connected with',waiting:'Waiting for the person you invited.',save:'Save',saved:'Saved.',profileError:'Could not save your profile.',loadError:'Could not load your account.',closeTitle:'End this connection?',closeMessage:'Both people keep their past connection. Pebbles can no longer travel or be touched here.',cancel:'Cancel',deleteTitle:'Delete account?',deleteMessage:'Your profile, connections, sent events, invitations, and device tokens will be removed. The other person keeps their own data.',deleteError:'Could not delete account.'},
  language:{title:'Language',system:'System default',english:'English',hungarian:'Magyar'},
} as const;
