export const hu = {
  app:{name:'Pebble',loading:'A Pebble betöltése',retry:'Próbáld újra',connectionError:'A kapcsolat betöltése nem sikerült.',settings:'Beállítások',back:'Vissza',bowlHome:'Vissza a táladhoz',notConfigured:'A Pebble nincs beállítva ezen az eszközön.',continue:'Tovább',skip:'Kihagyás'},
  onboarding:{first:'Egy kavics azt jelenti: gondoltam rád.',second:'Ugyanazok a kavicsok vándorolnak a két tál között.',third:'Nem kell válaszolni. Az üres tál csendben maradhat.'},
  auth:{signIn:'Belépés',createProfile:'Profil létrehozása',access:'Lépj be a privát kapcsolatodba.',displayName:'Megjelenő név',email:'E-mail',password:'Jelszó',createAccount:'Profil létrehozása',existingAccount:'Már van hozzáférésem',createError:'A profil létrehozása nem sikerült.',signInError:'A belépés nem sikerült.',emailHint:'Adj meg érvényes e-mail-címet.',passwordHint:'Legalább 6 karaktert használj.'},
  pairing:{begin:'Kapcsolódás létrehozása.',create:'Meghívó létrehozása',join:'Csatlakozás meghívóval',joinChoice:'Meghívóval csatlakozom',joinTitle:'Csatlakozás meghívóval.',joinAction:'Csatlakozás',useOther:'Másik meghívó használata',waitingTitle:'A tálad készen áll.',waitingSecondary:'A másik személy még nem csatlakozott.',invitation:'Meghívókód',shareOnce:'Ez a meghívó egyszer használható. Csak annak küldd el, akit választottál.',copy:'Meghívó másolása',share:'Meghívó megosztása',copied:'A meghívó a vágólapra került.',createError:'A kapcsolat létrehozása nem sikerült.',joinError:'A csatlakozás nem sikerült.',activeConnection:'Már van aktív kapcsolatod.',invalid:'Ez a meghívó nem elérhető.',expired:'Ez a meghívó lejárt.',used:'Ezt a meghívót már felhasználták.',full:'Ebben a kapcsolatban már ketten vannak.',network:'Nem sikerült kapcsolódni. Próbáld újra.',waiting:'A tálad készen áll. A másik személy még nem csatlakozott.'},
  bowl:{title:'A tálad',empty:'A tál most üres.',accessibility:'A tálad és a nálad lévő kavicsok',incoming:'Újonnan érkezett kavics',held:'Kavics a táladban',holdHint:'Érints meg egy kavicsot a felemeléshez. A kijelölt kavicsot hosszan nyomva küldheted el.',selectAccessibilityHint:'Jelöld ki ezt a kavicsot a megtekintéshez.',sendAccessibilityHint:'Küldd el a kijelölt kavicsot.',selectAccessibilityAction:'Kavics kijelölése',sendAccessibilityAction:'Kijelölt kavics küldése',touchAccessibilityHint:'Érintsd meg, vagy jelöld ki a megtekintéshez.',loading:'A tálad betöltése',closed:'Ez a kapcsolat lezárult.',sendError:'A kavics most nem tudott elindulni. Próbáld újra.',touchError:'A kavicsot most nem sikerült megérinteni. Próbáld újra.',loadError:'A tálad betöltése nem sikerült.'},
  settings:{title:'Beállítások',profile:'Profil',language:'Nyelv',connection:'Kapcsolat',notifications:'Értesítések',account:'Fiók',development:'Fejlesztés',bowlLab:'Bowl Lab megnyitása',glLayoutProbe:'GL Layout Probe',rawGLViewProbe:'Raw GLView Probe',r3fViewportProbe:'R3F Viewport Probe',developmentOnly:'Csak fejlesztői buildben érhető el.',displayName:'Megjelenő név',accountEmail:'Fiók e-mail-címe',currentLanguage:'Jelenlegi nyelv',systemDefault:'Rendszer alapértelmezése',activeConnection:'Aktív kapcsolat',pastConnections:'Korábbi kapcsolatok',permission:'Értesítési engedély',sounds:'Hangok',soundsDetail:'Halk tálhangok, ha elkészülnek a felvételek',enabled:'Engedélyezve',disabled:'Nincs engedélyezve',unavailable:'Nem érhető el',signOut:'Kijelentkezés',deleteAccount:'Fiók törlése',endConnection:'Kapcsolat lezárása',beginNew:'Kapcsolódás létrehozása',noPast:'Még nincs korábbi kapcsolat.',statusActive:'Kapcsolódva',statusWaiting:'Várakozik',statusClosed:'Lezárt',partner:'Kapcsolatban vele:',waiting:'Arra vár, akit meghívtál.',save:'Mentés',saved:'Elmentve.',profileError:'A profil mentése nem sikerült.',loadError:'A fiók betöltése nem sikerült.',closeTitle:'Lezárod ezt a kapcsolatot?',closeMessage:'Mindketten megőrzitek a korábbi kapcsolatot. Itt több kavics nem indulhat el és nem érinthető meg.',cancel:'Mégse',deleteTitle:'Törlöd a fiókot?',deleteMessage:'A profilod, kapcsolataid, küldési eseményeid, meghívóid és eszköztokenjeid törlődnek. A másik személy a saját adatait megőrzi.',deleteError:'A fiók törlése nem sikerült.'},
  language:{title:'Nyelv',system:'Rendszer alapértelmezése',english:'English',hungarian:'Magyar'},
} as const;
