import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, fonts, MIN_TOUCH_TARGET, radii, spacing } from '../../design/tokens';
import { useI18n } from '../../i18n';
import { requireSupabaseClient } from '../../lib/supabase';
import { BowlScene } from '../bowl/BowlScene';
import { useBowlEnvironment } from '../bowl/bowlEnvironment';
import { useReducedMotion } from '../bowl/useReducedMotion';
import { createConnectionWithInvite, getLocalInvitation, joinConnectionWithInvite, type ConnectionInvite } from './connectionService';

export function PairingScreen({existingPairId,onPaired}:{existingPairId?:string|null;onPaired:()=>void}){const{t}=useI18n();const environment=useBowlEnvironment();const reducedMotion=useReducedMotion();const[code,setCode]=useState('');const[created,setCreated]=useState<ConnectionInvite|null>(null);const[error,setError]=useState<string|null>(null);const[pending,setPending]=useState(false);const[copied,setCopied]=useState(false);
  useEffect(()=>{if(!existingPairId||created)return;void getLocalInvitation(existingPairId).then((inviteToken)=>{if(inviteToken)setCreated({pairId:existingPairId,inviteToken,expiresAt:''});});},[created,existingPairId]);
  useEffect(()=>{const pairId=created?.pairId??existingPairId;if(!pairId)return;const client=requireSupabaseClient();const check=async()=>{const{count}=await client.from('pair_members').select('user_id',{count:'exact',head:true}).eq('pair_id',pairId);if((count??0)>=2)onPaired();};const channel=client.channel(`connection-join:${pairId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'pair_members',filter:`pair_id=eq.${pairId}`},()=>void check()).subscribe((status)=>{if(status==='SUBSCRIBED')void check();});return()=>{void client.removeChannel(channel);};},[created?.pairId,existingPairId,onPaired]);
  const create=async()=>{setPending(true);setError(null);try{setCreated(await createConnectionWithInvite());}catch{setError(t('pairing.createError'));}finally{setPending(false);}};
  const join=async()=>{if(!code.trim()||pending)return;setPending(true);setError(null);try{await joinConnectionWithInvite(code);onPaired();}catch{setError(t('pairing.joinError'));}finally{setPending(false);}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.visual}><BowlScene pebbles={[]} environment={environment} disabled reducedMotion={reducedMotion} onSend={async()=>{}} onTouch={async()=>{}}/>{created?<View pointerEvents="none" style={styles.secondBowl}/>:null}</View>
    <Text style={styles.title}>{t('pairing.begin')}</Text>
    {created?<View style={styles.invitation}><Text style={styles.relational}>{t('pairing.waiting')}</Text><Text selectable style={styles.code}>{created.inviteToken}</Text><Text style={styles.helper}>{t('pairing.shareOnce')}</Text><View style={styles.actions}><Pressable accessibilityRole="button" onPress={()=>void Clipboard.setStringAsync(created.inviteToken).then(()=>setCopied(true))} style={styles.quietButton}><Text style={styles.link}>{copied?t('pairing.copied'):t('pairing.copy')}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>void Share.share({message:created.inviteToken})} style={styles.quietButton}><Text style={styles.link}>{t('pairing.share')}</Text></Pressable></View></View>:existingPairId?<Text style={styles.relational}>{t('pairing.waiting')}</Text>:<Pressable accessibilityRole="button" disabled={pending} onPress={()=>void create()} style={[styles.primary,pending&&styles.disabled]}>{pending?<ActivityIndicator color={colors.textPrimary}/>:<Text style={styles.primaryText}>{t('pairing.create')}</Text>}</Pressable>}
    <View style={styles.divider}/><Text style={styles.label}>{t('pairing.join')}</Text><TextInput accessibilityLabel={t('pairing.invitation')} autoCapitalize="none" autoCorrect={false} returnKeyType="done" onSubmitEditing={()=>void join()} onChangeText={setCode} placeholder={t('pairing.invitation')} placeholderTextColor="#747B80" selectionColor={colors.warmKey} style={styles.input} value={code}/><Pressable accessibilityRole="button" disabled={pending||!code.trim()} onPress={()=>void join()} style={[styles.secondary,(pending||!code.trim())&&styles.disabled]}><Text style={styles.secondaryText}>{t('pairing.join')}</Text></Pressable>
    {error?<Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>:null}
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.atmosphere},content:{paddingHorizontal:spacing.lg,paddingBottom:spacing.xxl},visual:{height:260,marginHorizontal:-spacing.lg},secondBowl:{position:'absolute',right:'8%',bottom:34,width:92,height:38,borderRadius:999,borderWidth:8,borderColor:'rgba(112,119,121,.26)'},title:{fontFamily:fonts.relational,fontSize:30,lineHeight:38,color:colors.textPrimary,textAlign:'center',marginBottom:spacing.xl},relational:{fontFamily:fonts.relational,fontSize:20,lineHeight:28,color:colors.textPrimary},invitation:{gap:spacing.md},code:{fontFamily:fonts.system,fontSize:13,lineHeight:20,color:colors.textSubdued,padding:spacing.md,borderRadius:radii.input,backgroundColor:colors.surface},helper:{fontFamily:fonts.system,fontSize:14,lineHeight:20,color:colors.textSubdued},actions:{flexDirection:'row',gap:spacing.md},quietButton:{minHeight:MIN_TOUCH_TARGET,justifyContent:'center'},link:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:15},primary:{minHeight:54,alignItems:'center',justifyContent:'center',borderRadius:radii.control,backgroundColor:'#5B625F'},primaryText:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:16},divider:{height:1,backgroundColor:colors.border,marginVertical:spacing.xl},label:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:16,marginBottom:spacing.sm},input:{minHeight:54,borderWidth:1,borderColor:colors.border,borderRadius:radii.input,paddingHorizontal:spacing.md,color:colors.textPrimary,backgroundColor:colors.surface,fontFamily:fonts.system,fontSize:16},secondary:{minHeight:54,marginTop:spacing.sm,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:radii.control},secondaryText:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:16},disabled:{opacity:.42},error:{fontFamily:fonts.system,color:colors.error,fontSize:14,textAlign:'center',marginTop:spacing.md}});
