import { Pressable, StyleSheet, Text, View } from 'react-native';
import { LuminousButton } from '../../design/LuminousButton';
import { componentTokens } from '../../design/componentTokens';
import { colors, MIN_TOUCH_TARGET, spacing, typography } from '../../design/tokens';

export function PairingWaitingState({ title, secondary, token, helper, copyLabel, shareLabel, copiedMessage, alternativeLabel, pending, reducedMotion, onCopy, onShare, onAlternative }: { title: string; secondary: string; token: string | null; helper: string; copyLabel: string; shareLabel: string; copiedMessage: string | null; alternativeLabel: string; pending: boolean; reducedMotion: boolean; onCopy: () => void; onShare: () => void; onAlternative: () => void }) {
  return <View style={styles.content}><View style={styles.copy}><Text accessibilityRole="header" style={styles.title}>{title}</Text><Text style={styles.secondary}>{secondary}</Text></View>{token ? <><View style={styles.tokenSurface}><Text selectable accessibilityLabel={helper} style={styles.token}>{token}</Text></View><Text style={styles.helper}>{helper}</Text><View style={styles.actions}><LuminousButton label={copyLabel} disabled={pending} reducedMotion={reducedMotion} onPress={onCopy} /><LuminousButton label={shareLabel} variant="secondary" disabled={pending} reducedMotion={reducedMotion} onPress={onShare} /></View></> : null}{copiedMessage ? <Text accessibilityLiveRegion="polite" style={styles.copied}>{copiedMessage}</Text> : null}<Pressable accessibilityRole="button" accessibilityState={{ expanded: false }} onPress={onAlternative} style={styles.disclosure}><Text style={styles.disclosureText}>{alternativeLabel}</Text><Text style={styles.disclosureIcon}>＋</Text></Pressable></View>;
}

const styles = StyleSheet.create({ content: { gap: spacing.md }, copy: { alignItems: 'center', gap: spacing.xs }, title: { ...typography.relationalHero, color: colors.relationalPrimary, textAlign: 'center' }, secondary: { ...typography.functionalSecondary, color: colors.textSubdued, textAlign: 'center' }, tokenSurface: { padding: spacing.md, borderRadius: componentTokens.invitation.radius, borderWidth: 1, borderColor: componentTokens.invitation.border, backgroundColor: componentTokens.invitation.background }, token: { fontFamily: 'monospace', color: colors.textPrimary, fontSize: 13, lineHeight: 21, flexWrap: 'wrap' }, helper: { ...typography.functionalSecondary, color: colors.textSubdued }, actions: { gap: spacing.sm }, copied: { ...typography.functionalSecondary, color: colors.primaryPressed, textAlign: 'center' }, disclosure: { minHeight: MIN_TOUCH_TARGET, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs }, disclosureText: { ...typography.functionalSecondary, color: colors.textPrimary }, disclosureIcon: { ...typography.functionalPrimary, color: colors.textSubdued } });
