import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { deletePebbleAccount } from '../lifecycle/lifecycleService';
import { requireSupabaseClient } from '../../lib/supabase';
import { useI18n } from '../../i18n';
export function AccountScreen() { const { t } = useI18n(); const router = useRouter(); const [error, setError] = useState<string | null>(null); const signOut = async () => { setError(null); try { await requireSupabaseClient().auth.signOut({ scope: 'local' }); router.replace('/(auth)'); } catch { setError(t('settings.loadError')); } }; const remove = () => Alert.alert(t('settings.deleteTitle'), t('settings.deleteMessage'), [{text:t('settings.cancel'),style:'cancel'},{text:t('settings.deleteAccount'),style:'destructive',onPress:() => void deletePebbleAccount().catch(() => setError(t('settings.deleteError')))}]); return <SafeAreaView style={styles.safe}><View style={styles.content}><Pressable accessibilityRole="button" onPress={() => void signOut()} style={styles.button}><Text style={styles.buttonText}>{t('settings.signOut')}</Text></Pressable><Pressable accessibilityRole="button" onPress={remove} style={styles.delete}><Text style={styles.deleteText}>{t('settings.deleteAccount')}</Text></Pressable>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</View></SafeAreaView>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F3EC'},content:{padding:28,gap:12},button:{minHeight:52,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'#CBBEAE',borderRadius:26},buttonText:{color:'#403931',fontSize:16,fontWeight:'600'},delete:{alignSelf:'center',minHeight:44,justifyContent:'center',marginTop:24},deleteText:{color:'#8B3F35',fontSize:14,fontWeight:'600'},error:{color:'#8B3F35',textAlign:'center'}});
