import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useAuthSession } from '../auth/useAuthSession';
import { getLocalInvitation, getShoreConnections, type ClosedShore, type ShoreConnection } from '../pairing/pairingService';
import { closeShore } from '../lifecycle/lifecycleService';
import { useI18n } from '../../i18n';
export function ConnectionScreen() { const { session } = useAuthSession(); const { t } = useI18n(); const router = useRouter(); const [active, setActive] = useState<ShoreConnection | null>(null); const [closed, setClosed] = useState<ClosedShore[]>([]); const [invite, setInvite] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const refresh = useCallback(async () => { if (!session) return; try { const connections = await getShoreConnections(session.user.id); setActive(connections.active); setClosed(connections.closed); setInvite(connections.active?.hasPendingInvite ? await getLocalInvitation(connections.active.id) : null); } catch { setError(t('settings.loadError')); } }, [session, t]); useEffect(() => { const timeout = setTimeout(() => { void refresh(); }, 0); return () => clearTimeout(timeout); }, [refresh]); const confirmClose = () => { if (!active) return; Alert.alert(t('settings.closeTitle'), t('settings.closeMessage'), [{text:t('settings.cancel'),style:'cancel'},{text:t('settings.closeShore'),style:'destructive',onPress:() => void closeShore(active.id).then(() => { void refresh(); router.replace('/(app)/pairing'); }).catch(() => setError(t('settings.loadError')))}]); }; return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.heading}>{t('settings.activeShore')}</Text>{active ? <View style={styles.card}><Text style={styles.status}>{active.partnerName ? t('settings.statusActive') : t('settings.statusWaiting')}</Text><Text style={styles.partner}>{active.partnerName ? `${t('settings.partner')}: ${active.partnerName}` : t('settings.waiting')}</Text>{invite ? <Text selectable style={styles.invite}>{invite}</Text> : null}<Pressable accessibilityRole="button" onPress={confirmClose} style={styles.close}><Text style={styles.closeText}>{t('settings.closeShore')}</Text></Pressable></View> : <Pressable accessibilityRole="button" onPress={() => router.push('/(app)/pairing')} style={styles.begin}><Text style={styles.beginText}>{t('settings.beginNew')}</Text></Pressable>}<Text style={styles.heading}>{t('settings.closedShores')}</Text>{closed.length ? closed.map((shore) => <Pressable key={shore.id} accessibilityRole="button" onPress={() => router.push(`/(app)/shore/${shore.id}`)} style={styles.history}><Text style={styles.status}>{t('settings.statusClosed')}</Text></Pressable>) : <Text style={styles.empty}>{t('settings.noClosed')}</Text>}{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</View></SafeAreaView>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F3EC'},content:{padding:28,gap:10},heading:{color:'#776D62',fontSize:13,fontWeight:'700',letterSpacing:.6,marginTop:16},card:{gap:10,borderWidth:1,borderColor:'#D8CCBE',borderRadius:12,padding:16,backgroundColor:'#FBF8F2'},status:{color:'#403931',fontSize:16,fontWeight:'600'},partner:{color:'#675D52',fontSize:14},invite:{color:'#403931',fontSize:12},close:{alignSelf:'flex-start',minHeight:40,justifyContent:'center'},closeText:{color:'#8B3F35',fontWeight:'600'},begin:{minHeight:52,borderRadius:26,justifyContent:'center',alignItems:'center',backgroundColor:'#4F6A5F'},beginText:{color:'#F7F3EC',fontSize:16,fontWeight:'600'},history:{minHeight:54,justifyContent:'center',borderBottomWidth:1,borderBottomColor:'#E0D7CA'},empty:{color:'#776D62'},error:{color:'#8B3F35',textAlign:'center'}});
