import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, fonts, MIN_TOUCH_TARGET, spacing } from '../../design/tokens';
import { useI18n } from '../../i18n';
import { useAppSession } from '../app/AppSessionProvider';
import { closeConnection } from '../lifecycle/lifecycleService';
import { getConnections, getLocalInvitation, type ConnectionSummary, type PastConnection } from '../pairing/connectionService';

export function ConnectionScreen(){const{session,connectionRefresh}=useAppSession();const{t}=useI18n();const router=useRouter();const[active,setActive]=useState<ConnectionSummary|null>(null);const[past,setPast]=useState<PastConnection[]>([]);const[invite,setInvite]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const refresh=useCallback(async()=>{if(!session)return;try{setError(null);const result=await getConnections(session.user.id);setActive(result.active);setPast(result.past);setInvite(result.active?.hasPendingInvite?await getLocalInvitation(result.active.id):null);}catch{setError(t('settings.loadError'));}},[session,t]);useEffect(()=>{const timer=setTimeout(()=>void refresh(),0);return()=>clearTimeout(timer);},[refresh]);const end=()=>{if(!active)return;Alert.alert(t('settings.closeTitle'),t('settings.closeMessage'),[{text:t('settings.cancel'),style:'cancel'},{text:t('settings.endConnection'),style:'destructive',onPress:()=>void closeConnection(active.id).then(async()=>{await refresh();await connectionRefresh();router.replace('/(app)/pairing');}).catch(()=>setError(t('settings.loadError')))}]);};return<SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>{t('settings.activeConnection')}</Text>{active?<View style={styles.section}><Text style={styles.status}>{active.partnerName?t('settings.statusActive'):t('settings.statusWaiting')}</Text><Text style={styles.detail}>{active.partnerName?`${t('settings.partner')} ${active.partnerName}`:t('settings.waiting')}</Text>{invite?<Text selectable style={styles.invite}>{invite}</Text>:null}<Pressable accessibilityRole="button" onPress={end} style={styles.destructive}><Text style={styles.destructiveText}>{t('settings.endConnection')}</Text></Pressable></View>:<Pressable accessibilityRole="button" onPress={()=>router.push('/(app)/pairing')} style={styles.primary}><Text style={styles.primaryText}>{t('settings.beginNew')}</Text></Pressable>}<Text style={styles.heading}>{t('settings.pastConnections')}</Text>{past.length?past.map((item)=><Pressable key={item.id} accessibilityRole="button" accessibilityLabel={t('settings.statusClosed')} onPress={()=>router.push(`/(app)/bowl/${item.id}`)} style={styles.row}><Text style={styles.rowText}>{t('settings.statusClosed')}</Text><Text style={styles.arrow}>›</Text></Pressable>):<Text style={styles.empty}>{t('settings.noPast')}</Text>}{error?<Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>:null}</ScrollView></SafeAreaView>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.atmosphere},content:{padding:spacing.lg,paddingBottom:spacing.xxl},heading:{fontFamily:fonts.systemSemibold,color:colors.textSubdued,fontSize:12,letterSpacing:.8,textTransform:'uppercase',marginTop:spacing.lg,marginBottom:spacing.sm},section:{gap:spacing.sm,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.border},status:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:17},detail:{fontFamily:fonts.system,color:colors.textSubdued,fontSize:15,lineHeight:22},invite:{fontFamily:fonts.system,color:colors.textSubdued,fontSize:12,lineHeight:18,backgroundColor:colors.surface,padding:spacing.md,borderRadius:12},destructive:{alignSelf:'flex-start',minHeight:MIN_TOUCH_TARGET,justifyContent:'center',marginTop:spacing.md},destructiveText:{fontFamily:fonts.systemMedium,color:colors.error,fontSize:14},primary:{minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:26,backgroundColor:'#5B625F'},primaryText:{fontFamily:fonts.systemMedium,color:colors.textPrimary,fontSize:16},row:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.border},rowText:{fontFamily:fonts.system,color:colors.textPrimary,fontSize:16},arrow:{fontFamily:fonts.system,color:colors.textSubdued,fontSize:24},empty:{fontFamily:fonts.system,color:colors.textSubdued,fontSize:15,paddingVertical:spacing.md},error:{fontFamily:fonts.system,color:colors.error,textAlign:'center',marginTop:spacing.md}});
