import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, fonts, spacing } from '../../design/tokens';
import { BowlScene } from './BowlScene';
import { getBowlEnvironment } from './bowlEnvironment';
import { TOTAL_PAIR_PEBBLES, type HeldPebble } from './bowlTypes';

const seeds=[112358,271828,314159,161803,141421,173205,223606,244948];
function Chip({label,active,onPress}:{label:string;active?:boolean;onPress:()=>void}){return<Pressable onPress={onPress} style={[styles.chip,active&&styles.active]}><Text style={styles.chipText}>{label}</Text></Pressable>;}
export function BowlLabScreen(){const[count,setCount]=useState(4);const[phase,setPhase]=useState(12);const[month,setMonth]=useState(6);const[reduced,setReduced]=useState(false);const[fallback,setFallback]=useState(false);const[incoming,setIncoming]=useState(false);const[large,setLarge]=useState(false);const pebbles=useMemo<HeldPebble[]>(()=>seeds.slice(0,count).map((visualSeed,index)=>({id:`lab-${visualSeed}`,visualSeed,transferEventId:index===count-1&&incoming?'lab-event':null,incoming:index===count-1&&incoming,touched:!(index===count-1&&incoming)})),[count,incoming]);const environment=getBowlEnvironment(new Date(2026,month,15,phase));return<SafeAreaView style={styles.safe}><View style={[styles.preview,large&&styles.small]}><BowlScene pebbles={pebbles} environment={environment} reducedMotion={reduced} forceFallback={fallback} onSend={async(id)=>setCount((value)=>Math.max(0,value-1))} onTouch={async()=>setIncoming(false)}/></View><ScrollView contentContainerStyle={styles.controls}><Text style={styles.label}>Pebbles</Text><View style={styles.wrap}>{Array.from({length:TOTAL_PAIR_PEBBLES+1},(_,value)=><Chip key={value} label={String(value)} active={count===value} onPress={()=>setCount(value)}/>)}</View><Text style={styles.label}>Lighting</Text><View style={styles.wrap}>{[[7,'Morning'],[12,'Day'],[18,'Evening'],[23,'Night']].map(([value,label])=><Chip key={label} label={String(label)} active={phase===value} onPress={()=>setPhase(Number(value))}/>)}</View><Text style={styles.label}>Season</Text><View style={styles.wrap}>{[[0,'Winter'],[3,'Spring'],[6,'Summer'],[9,'Autumn']].map(([value,label])=><Chip key={label} label={String(label)} active={month===value} onPress={()=>setMonth(Number(value))}/>)}</View><View style={styles.wrap}><Chip label="Incoming" active={incoming} onPress={()=>setIncoming(!incoming)}/><Chip label="Reduced motion" active={reduced} onPress={()=>setReduced(!reduced)}/><Chip label="GL fallback" active={fallback} onPress={()=>setFallback(!fallback)}/><Chip label="Small / large type" active={large} onPress={()=>setLarge(!large)}/></View><Text style={[styles.serif,large&&styles.large]}>The bowl is empty.</Text><Text style={[styles.serif,large&&styles.large]}>A tál most üres. ő Ő ű Ű</Text></ScrollView></SafeAreaView>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.atmosphere},preview:{height:390},small:{height:290,marginHorizontal:44},controls:{padding:spacing.md,paddingBottom:spacing.xxl},label:{fontFamily:fonts.systemSemibold,color:colors.textSubdued,fontSize:12,marginTop:spacing.md,marginBottom:spacing.sm},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:42,justifyContent:'center',paddingHorizontal:12,borderRadius:21,borderWidth:1,borderColor:colors.border},active:{backgroundColor:'#4D5754'},chipText:{fontFamily:fonts.systemMedium,color:colors.textPrimary},serif:{fontFamily:fonts.relational,color:colors.textPrimary,fontSize:20,lineHeight:28,marginTop:spacing.md},large:{fontSize:32,lineHeight:42}});
